version: '2.0'

services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db

  edubuddy:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/edubuddy_data
    ports:
      - "8300:3000"
      - "8550:5500"
    restart: always

volumes:
  mongo-data: